[package]
name = "tabld"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
indexmap = { version = "2.14.0", features = ["serde"] }
itertools = "0.14.0"
quick-xml = "0.40.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.150", features = ["preserve_order"] }
tree-sitter = "0.20.6"
tree-sitter-manchester = { git = "https://github.com/ckindermann/tree-sitter-manchester" }
