// Read and write RDFXML like OWL API does.

use std::cmp::Ordering;
use std::collections::{BTreeMap, BTreeSet};
use std::io::Cursor;

use itertools::Itertools;
use quick_xml::events::attributes::Attribute;
use quick_xml::events::{BytesDecl, BytesEnd, BytesStart, BytesText, Event};
use quick_xml::name::QName;
use quick_xml::reader::Reader;
use quick_xml::{Error as XMLError, Writer};

use crate::model::{
    CLASS, Graph, INTERSECTION_OF, IndexedMemoryGraph, MemoryGraph, ON_PROPERTY, Object, Objects,
    PLAIN, Predicates, RESTRICTION, SOME_VALUES_FROM, Subject, TYPE, Triple,
};
use crate::prefix::Prefixes;

const DEBUG: bool = false;

// Read prefixes from an attribute_raw() string
fn read_prefixes(content: &str) -> Result<Prefixes, XMLError> {
    let mut prefixes = Prefixes::new();
    let name = "root";
    let elem = BytesStart::from_content(format!("{name}{content}"), name.len());
    for attr in elem.attributes() {
        match attr {
            Ok(attr) => match attr.key.prefix() {
                Some(p) => {
                    if p.into_inner() == "xmlns".as_bytes() {
                        let prefix = String::from_utf8(attr.key.local_name().into_inner().to_vec())
                            .expect("Valid local name");
                        let iri = String::from_utf8(attr.value.into_owned())
                            .expect("Valid attribute value");
                        prefixes.insert(&prefix, &iri);
                    }
                }
                None => continue,
            },
            Err(_) => continue,
        }
    }
    Ok(prefixes)
}

fn read_qname(qname: QName<'_>) -> String {
    format!(
        "{}:{}",
        str::from_utf8(
            qname
                .prefix()
                .unwrap_or(QName(b"PREFIX:LOCAL").prefix().unwrap())
                .into_inner()
        )
        .unwrap_or("PREFIX"),
        str::from_utf8(qname.local_name().into_inner()).unwrap_or("LOCAL")
    )
}

// Read an attribute value to a string
fn read_attr(a: Attribute<'_>) -> String {
    String::from_utf8(a.value.into_owned()).expect("Valid attribute value")
}

// Read a string into a MemoryGraph.
pub fn read(input: &str) -> Result<MemoryGraph, XMLError> {
    let mut reader = Reader::from_str(input);

    // TODO: generalize this
    let name = "http://example.com/graph";
    let mut graph = MemoryGraph::from_id(name);

    // root rdf:RDF element
    let start;
    loop {
        match reader.read_event()? {
            Event::Start(event) => {
                start = event.clone();
                break;
            }
            Event::Eof => panic!("No root element"),
            _ => continue,
        }
    }
    let qname = read_qname(start.name());
    if qname != "rdf:RDF" {
        panic!("Document does not use RDFXML format");
    }

    let value = str::from_utf8(start.attributes_raw()).expect("Valid attributes");
    let prefixes = read_prefixes(&value)?;

    // Store prefixes
    let name = prefixes.expand(name);
    let mut doc = Subject::from_name(&name);
    doc.insert("http://example.com/rdf_declarations", Object::string(value));

    loop {
        match reader.read_event() {
            Err(e) => panic!("Error at position {}: {:?}", reader.error_position(), e),

            // exits the loop when reaching end of file
            Ok(Event::Eof) => {
                graph.insert(doc);
                return Ok(graph);
            }

            // A Subject with predicates.
            Ok(Event::Start(start)) => {
                let subject = read_subject(&mut reader, &prefixes, &start, 1)?;
                if subject.has_type("http://www.w3.org/2002/07/owl#Ontology") {
                    graph.set_id(&subject.name());
                }
                graph.insert(subject);
            }

            // A Subject with only an rdf:type predicate.
            Ok(Event::Empty(start)) => {
                let qname = read_qname(start.name());
                let iri = match start.try_get_attribute("rdf:about")? {
                    Some(a) => {
                        String::from_utf8(a.value.into_owned()).expect("Valid attribute value")
                    }
                    None => panic!("Top-level <{qname}/> element missing rdf:about attribute"),
                };
                if DEBUG {
                    println!(r#"    <{qname} rdf:about="{iri}"/>"#);
                }
                let rdf_type = &prefixes.expand(&qname);
                let mut subject = Subject::from_name(&iri);
                subject.insert_type(rdf_type);
                if subject.has_type("http://www.w3.org/2002/07/owl#Ontology") {
                    graph.set_id(&subject.name());
                }
                graph.insert(subject);
            }

            // Store this special final comment generated by OWL API.
            Ok(Event::Comment(comment)) => {
                let comment = comment.decode().expect("Valid text").into_owned();
                if comment.starts_with(" Generated by the OWL API (version ") {
                    doc.insert("http://example.com/rdf_generator", Object::string(&comment));
                }
            }

            _ => continue,
        }
    }
}

// Read a BytesStart from a non-empty start element as a Subject.
fn read_subject(
    reader: &mut Reader<&[u8]>,
    prefixes: &Prefixes,
    start: &BytesStart<'_>,
    depth: usize,
) -> Result<Subject, XMLError> {
    let qname = read_qname(start.name());
    let rdf_type = prefixes.expand(&qname);
    let mut subject = Subject::from_type(&rdf_type);

    // The rdf:about attribute holds the Subject's id,
    // if it exists.
    match start.try_get_attribute("rdf:about")? {
        Some(a) => {
            let name = String::from_utf8(a.value.into_owned()).expect("Valid attribute value");
            subject.set_name(&name);
        }
        None => (),
    };
    if DEBUG {
        if subject.name() != "" {
            println!(
                r#"{}<{qname} rdf:about="{}">"#,
                "    ".repeat(depth),
                subject.name()
            );
        } else {
            println!("{}<{qname}>", "    ".repeat(depth));
        }
    }
    loop {
        match reader.read_event()? {
            Event::Start(event) => {
                // could be: lang literal, typed literal, plain literal, collection of objects, or a single anonymous nested subject
                let qname = read_qname(event.name());
                let predicate = prefixes.expand(&qname);
                let object = read_object(reader, &prefixes, &event, depth + 1)?;
                subject.insert(&predicate, object);
            }
            Event::Empty(event) => {
                // must be an IRI in an rdf:resource
                // or a blank node with an rdf:nodeID
                let qname = read_qname(event.name());
                let predicate = prefixes.expand(&qname);
                match event.try_get_attribute("rdf:resource")? {
                    Some(a) => {
                        let iri: String = read_attr(a);
                        if DEBUG {
                            println!(
                                r#"{}<{qname} rdf:resource="{iri}"/>"#,
                                "    ".repeat(depth + 1)
                            );
                        }
                        subject.insert(&predicate, Object::id(&iri));
                    }
                    None => match event.try_get_attribute("rdf:nodeID")? {
                        Some(a) => {
                            let id: String = read_attr(a);
                            if DEBUG {
                                println!(
                                    r#"{}<{qname} rdf:nodeID="{id}"/>"#,
                                    "    ".repeat(depth + 1)
                                );
                            }
                            subject.insert(&predicate, Object::id(&id));
                        }
                        None => panic!(
                            "Empty <{qname}/> predicate without rdf:resource or rdf:nodeID at {}",
                            reader.buffer_position()
                        ),
                    },
                };
            }
            Event::Text(event) => {
                let text = event.decode().expect("Valid text").into_owned();
                if !text.trim().is_empty() {
                    panic!(
                        "Unexpected non-whitespace text between predicates at {}: {text}",
                        reader.buffer_position()
                    );
                }
            }
            Event::GeneralRef(_) => {
                panic!(
                    "Unexpected entity between predicates at {}",
                    reader.buffer_position()
                );
            }
            Event::End(event) => {
                if DEBUG {
                    let qname = read_qname(event.name());
                    println!("{}</{qname}>", "    ".repeat(depth));
                }
                break;
            }
            _ => continue,
        }
    }

    // Top-level anonymous subject
    if subject.name() == "" && depth == 1 {
        subject.set_name_from_hash();
    }

    Ok(subject)
}

// Read a BytesStart from a non-empty start element as an Object.
fn read_object(
    reader: &mut Reader<&[u8]>,
    prefixes: &Prefixes,
    start: &BytesStart<'_>,
    depth: usize,
) -> Result<Object, XMLError> {
    let qname = read_qname(start.name());
    let predicate = prefixes.expand(&qname);

    // LanguageLiteral
    if let Some(a) = start.try_get_attribute("xml:lang")? {
        let language = read_attr(a);
        if DEBUG {
            print!(r#"{}<{qname} xml:lang="{language}">"#, "    ".repeat(depth));
        }
        let value = read_text(reader)?;
        return Ok(Object::lang(&value, &language));
    };

    // TypedLiteral
    if let Some(a) = start.try_get_attribute("rdf:datatype")? {
        let datatype = String::from_utf8(a.value.into_owned()).expect("Valid attribute value");
        if DEBUG {
            print!(
                r#"{}<{qname} rdf:datatype="{datatype}">"#,
                "    ".repeat(depth)
            );
        }
        let value = read_text(reader)?;
        return Ok(Object::typed(&value, &datatype));
    };

    // list of objects
    if let Some(a) = start.try_get_attribute("rdf:parseType")? {
        let parse_type = String::from_utf8(a.value.into_owned()).expect("Valid attribute value");
        if DEBUG {
            println!(
                "{}<{qname} rdf:parseType=\"{parse_type}\">",
                "    ".repeat(depth)
            );
        }
        if parse_type != "Collection" {
            panic!("element {predicate} has unknown rdf:parseType: {parse_type}");
        }
        let objects = read_objects(reader, &prefixes, depth)?;
        return Ok(Object::list(objects));
    };

    // Is next event text/ref (PLAIN) or element (rdf:type)?
    loop {
        match reader.read_event()? {
            // single anonymous nested subject
            Event::Start(inner_start) => {
                if DEBUG {
                    println!("{}<{qname}>", "    ".repeat(depth));
                }
                let subject2 = read_subject(reader, &prefixes, &inner_start, depth + 1)?;
                reader.read_to_end(start.name())?; // skip to end
                if DEBUG {
                    println!("{}</{qname}>", "    ".repeat(depth));
                }
                return Ok(Object::map(subject2.predicates()));
            }
            // PLAIN literal
            Event::Text(event) => {
                let text = event.decode().expect("Valid text").into_owned();
                if text.trim().is_empty() {
                    // continue to the next non-whitespace
                    continue;
                }
                if DEBUG {
                    print!("{}<{qname}>{text}", "    ".repeat(depth));
                }
                let content = read_text(reader)?;
                return Ok(Object::plain(&format!("{text}{content}")));
            }
            // PLAIN literal starting with entity
            Event::GeneralRef(event) => {
                let mut text = event.decode().expect("Valid text").into_owned();
                text = format!("&{text};");
                if DEBUG {
                    print!("{text}");
                }
                let content = read_text(reader)?;
                return Ok(Object::plain(&format!("{text}{content}")));
            }
            // PLAIN literal with the empty string
            // Could this possibly be an empty subject?
            Event::End(event2) => {
                if DEBUG {
                    let qname2 = read_qname(event2.name());
                    print!("</{qname2}>");
                }
                return Ok(Object::plain(""));
            }
            Event::Empty(..) => {
                continue;
            }
            _ => panic!("Unexpected event {start:?}"),
        }
    }
}

// Read a series of objects.
fn read_objects(
    reader: &mut Reader<&[u8]>,
    prefixes: &Prefixes,
    depth: usize,
) -> Result<Vec<Object>, XMLError> {
    let mut objects = Vec::new();
    loop {
        match reader.read_event()? {
            // an rdf:type for an anonymous nested subject
            Event::Start(start) => {
                let subject = read_subject(reader, &prefixes, &start, depth + 1)?;
                objects.push(Object::map(subject.predicates()));
            }
            // an rdf:Description element
            Event::Empty(event) => {
                let qname = read_qname(event.name());
                let iri = match event.try_get_attribute("rdf:about")? {
                    Some(a) => read_attr(a),
                    // None => panic!("{qname} element missing rdf:about attribute"),
                    None => String::new(),
                };
                if DEBUG {
                    println!(
                        r#"{}<{qname} rdf:about="{iri}"/>"#,
                        "    ".repeat(depth + 1)
                    );
                }
                objects.push(Object::id(&iri));
            }
            Event::End(event) => {
                if DEBUG {
                    let qname = read_qname(event.name());
                    println!("{}</{qname}>", "    ".repeat(depth));
                }
                break;
            }
            _ => continue,
        }
    }
    Ok(objects)
}

// Read the text content of a literal
fn read_text(reader: &mut Reader<&[u8]>) -> Result<String, XMLError> {
    // This is only used for DEBUGing.
    let mut content: Vec<String> = Vec::new();
    loop {
        match reader.read_event()? {
            Event::Text(event) => {
                let text = event.decode().expect("Valid text").into_owned();
                if DEBUG {
                    print!("{text}");
                }
                content.push(text);
            }
            Event::GeneralRef(event) => {
                let mut text = event.decode().expect("Valid text").into_owned();
                text = format!("&{text};");
                if DEBUG {
                    print!("{text}");
                }
                content.push(text);
            }
            Event::End(event) => {
                if DEBUG {
                    let qname = read_qname(event.name());
                    println!("</{qname}>");
                };
                return Ok(content.join(""));
            }
            Event::Start(event) => {
                let qname = read_qname(event.name());
                panic!("start element <{qname}> inside literal");
            }
            Event::Empty(event) => {
                let qname = read_qname(event.name());
                panic!("empty element <{qname}/> inside literal");
            }
            _ => continue,
        }
    }
}

#[derive(Debug)]
struct Properties {
    object: BTreeSet<String>,
}

// write_file
// write_db_table_to_file(connection, table, path) -> Result<(), XMLError> {}
fn write_section(
    writer: &mut Writer<Cursor<Vec<u8>>>,
    graph: &IndexedMemoryGraph,
    prefixes: &Prefixes,
    properties: &Properties,
    title: &str,
    rdf_type: &str,
    subjects: &BTreeSet<String>,
) -> Result<(), XMLError> {
    // println!("Writing section {title}");

    if subjects.len() > 0 {
        writer.write_event(Event::Text(BytesText::new(
            "    


    ",
        )))?;
        writer.write_event(Event::Comment(BytesText::new(&format!(
            " 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // {title}
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     "
        ))))?;
        if title == "Annotations" || title == "General axioms" {
            writer.write_event(Event::Text(BytesText::new("\n\n")))?;
        } else {
            writer.write_event(Event::Text(BytesText::new(
                "

    

",
            )))?
        };
    }
    let mut sorted = subjects.into_iter().collect::<Vec<&String>>();
    sorted.sort();
    // WARN: This is a horrible hack, but it works ok for OBI.
    if title == "General axioms" {
        sorted.sort_by_key(|s| graph.get(s).expect("subject a to exist").types());
        sorted.reverse();
    }
    for subject in sorted.iter() {
        write_subject(
            writer,
            prefixes,
            properties,
            rdf_type,
            graph.get(subject).expect("subject to exist"),
        )?;
        if title != "Annotations"
            && title != "General axioms"
            && subject != sorted.iter().last().unwrap()
        {
            writer.write_event(Event::Text(BytesText::new(
                "    

",
            )))?;
        }
    }
    Ok(())
}

fn write_subject(
    writer: &mut Writer<Cursor<Vec<u8>>>,
    prefixes: &Prefixes,
    properties: &Properties,
    section_rdf_type: &str,
    subject: &Subject,
) -> Result<(), XMLError> {
    let mut rdf_type = section_rdf_type;
    let owl_types: BTreeSet<String> = subject.owl_types().iter().map(|s| s.to_string()).collect();
    let mut is_class = owl_types.contains(CLASS);

    // WARN: This is a hack for anonymous owl:Restrictions.
    if subject.name().starts_with("hash:") {
        if subject.has_type(RESTRICTION) {
            rdf_type = RESTRICTION;
            is_class = true;
        }
    }

    // Skip rdf:Description in a few edge cases
    if section_rdf_type == &iri(RDF, "Description") && is_class && owl_types.len() == 1 {
        return Ok(());
    }

    // Override the rdf_type in a few edge cases.
    if section_rdf_type == &iri(OWL, "NamedIndividual") && owl_types.contains(&iri(OWL, "Thing")) {
        rdf_type = "http://www.w3.org/2002/07/owl#Thing";
    } else if section_rdf_type == &iri(OWL, "Class")
        && owl_types == BTreeSet::from([String::from(&iri(RDF, "Description"))])
    {
        rdf_type = "http://www.w3.org/1999/02/22-rdf-syntax-ns#Description";
    }

    // OWL API adds comments before most terms.
    if rdf_type == &iri(OWL, "Ontology") {
        // pass
    } else if section_rdf_type == &iri(RDF, "Description") {
        // writer.write_indent()?;
        writer.write_event(Event::Text(BytesText::new("    ")))?;
    } else {
        writer.write_indent()?;
        writer.write_event(Event::Comment(BytesText::new(&format!(
            " {} ",
            subject.name()
        ))))?;
        writer.write_event(Event::Text(BytesText::new("\n\n    ")))?;
    };

    // OWL API sorts predicates in a special order.
    let first_predicates: Vec<String> = vec![
        // Special predicate order for owl:Ontology
        &iri(OWL, "versionIRI"),
        &iri(OWL, "imports"),
        "protege:defaultLanguage",
        "obo:IAO_0000589", // OBO foundry unique label
    ]
    .iter()
    .map(|s| s.to_string())
    .collect();
    // Special predicate order for OWL logic
    let mut logical_predicates: Vec<String> = vec![
        iri(RDFS, "subPropertyOf"),
        iri(OWL, "inverseOf"),
        iri(RDF, "type"),
        iri(OWL, "equivalentClass"),
        iri(RDFS, "subClassOf"),
        iri(RDFS, "domain"),
        iri(RDFS, "range"),
        iri(OWL, "onProperty"),
        iri(OWL, "someValuesFrom"),
        iri(OWL, "disjointWith"),
    ];
    let mut last_predicates: Vec<String> = vec![iri(OWL, "deprecated")];

    if rdf_type == &iri(OWL, "AnnotationProperty") {
        logical_predicates.retain(|p| p != &iri(RDFS, "subPropertyOf"));
        logical_predicates.retain(|p| p != &iri(RDFS, "range"));
        last_predicates.insert(0, iri(RDFS, "range"));
    }

    // Collect predicates that are not speecial.
    let mut predicates: Vec<String> = subject
        .predicates()
        .into_keys()
        .filter(|p| !first_predicates.contains(&p))
        .filter(|p| !logical_predicates.contains(&p))
        .filter(|p| !last_predicates.contains(&p))
        .unique()
        .collect();
    // sort predicates
    // object properties before annotation properties
    predicates.sort_by(|a_iri, b_iri| {
        match (
            properties.object.contains(a_iri),
            properties.object.contains(b_iri),
        ) {
            (true, true) => a_iri.cmp(&b_iri),
            (true, false) => Ordering::Less,
            (false, true) => Ordering::Greater,
            (false, false) => a_iri.cmp(&b_iri),
        }
    });
    predicates = vec![
        first_predicates,
        logical_predicates.clone(),
        predicates,
        last_predicates,
    ]
    .concat();

    let mut triples: Vec<Triple> = Vec::from_iter(subject.triples());
    if triples.len() == owl_types.len()
        || (rdf_type == &iri(OWL, "NamedIndividual") && owl_types.len() > 1)
        || (rdf_type == &iri(OWL, "Thing") && owl_types.len() > 1)
    {
        writer
            .create_element(prefixes.compact(rdf_type))
            .with_attribute(("rdf:about", subject.name().as_str()))
            .write_empty()?;
    } else {
        // Special ordering for OWL API
        triples.sort_by(|a, b| {
            a.subject
                .cmp(&b.subject)
                .then(a.predicate.cmp(&b.predicate))
                .then(
                    if a.predicate == iri(RDF, "type") && b.predicate == iri(RDF, "type") {
                        // rdf:type owl:NamedIndividual goes first
                        // TODO: handle IRI/CURIE
                        match (
                            a.object.object() == "http://www.w3.org/2002/07/owl#NamedIndividual",
                            b.object.object() == "http://www.w3.org/2002/07/owl#NamedIndividual",
                        ) {
                            (true, true) => Ordering::Equal,
                            (true, false) => Ordering::Less,
                            (false, true) => Ordering::Greater,
                            (false, false) => Ordering::Equal,
                        }
                    } else {
                        Ordering::Equal
                    },
                )
                .then(compare_objects(&a.object, &b.object))
                .then(
                    // sort datatypes
                    match (a.object.datatype().as_str(), b.object.datatype().as_str()) {
                        // rdf:PlainLiteral literals go first
                        (
                            "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral",
                            "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral",
                        ) => Ordering::Equal,
                        ("http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral", _) => {
                            Ordering::Less
                        }
                        (_, "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral") => {
                            Ordering::Greater
                        }
                        (a, b) => a.cmp(&b),
                    },
                )
                .then(a.object.annotation().cmp(&b.object.annotation()))
        });

        let element = if subject.name().starts_with("hash:") {
            writer.create_element(qname(&prefixes, rdf_type))
        } else {
            writer
                .create_element(qname(&prefixes, rdf_type))
                .with_attribute(("rdf:about", subject.name().as_str()))
        };
        element.write_inner_content(|writer| {
            for predicate in predicates.iter() {
                // Special cases where statements are split across
                // owl:Class, owl:NamedIndividual, and rdf:Description
                // elements.
                if owl_types.len() > 1 {
                    if rdf_type == &iri(OWL, "Class") && predicate == &iri(RDF, "type") {
                        continue;
                    } else if rdf_type == &iri(OWL, "Class")
                        && !logical_predicates.contains(&predicate)
                    {
                        continue;
                    } else if rdf_type == &iri(RDF, "Description")
                        && logical_predicates.contains(&predicate)
                    {
                        continue;
                    } else if rdf_type == &iri(OWL, "NamedIndividual") {
                        continue;
                    }
                }
                for triple in triples.iter() {
                    if &triple.predicate != predicate {
                        continue;
                    }
                    // Don't duplicate rdf:type
                    if predicate == &iri(RDF, "type") && triple.object.object() == rdf_type {
                        continue;
                    }
                    write_predicate_object(writer, prefixes, &triple.predicate, &triple.object)
                        .expect("Write element");
                }
            }
            Ok(())
        })?;
    }
    // OWLAPI inserts an extra newline after each term.
    writer.write_event(Event::Text(BytesText::new("\n")))?;
    Ok(())
}

fn compare_predicates(a: &Predicates, b: &Predicates) -> Ordering {
    let a_type = a
        .get(TYPE)
        .and_then(|os| os.first())
        .and_then(|o| o.as_id())
        .and_then(|s| Some(s.to_string()))
        .unwrap_or_default();
    let b_type = b
        .get(TYPE)
        .and_then(|os| os.first())
        .and_then(|o| o.as_id())
        .and_then(|s| Some(s.to_string()))
        .unwrap_or_default();
    match a_type.cmp(&b_type) {
        Ordering::Less => return Ordering::Less,
        Ordering::Equal => (),
        Ordering::Greater => return Ordering::Greater,
    };
    match (
        a.contains_key(INTERSECTION_OF),
        b.contains_key(INTERSECTION_OF),
    ) {
        (true, true) => (),
        (true, false) => return Ordering::Less,
        (false, true) => return Ordering::Greater,
        (false, false) => (),
    };
    match (
        a.contains_key(SOME_VALUES_FROM),
        b.contains_key(SOME_VALUES_FROM),
    ) {
        (true, true) => {
            match a.get(ON_PROPERTY).cmp(&b.get(ON_PROPERTY)) {
                Ordering::Less => return Ordering::Less,
                Ordering::Equal => (),
                Ordering::Greater => return Ordering::Greater,
            };
            return compare_objects(
                a.get(SOME_VALUES_FROM)
                    .unwrap()
                    .first()
                    .expect("inner compare object a"),
                b.get(SOME_VALUES_FROM)
                    .unwrap()
                    .first()
                    .expect("inner compare object b"),
            );
        }
        (true, false) => return Ordering::Less,
        (false, true) => return Ordering::Greater,
        (false, false) => (),
    };
    a.cmp(&b)
}

fn compare_objects(a: &Object, b: &Object) -> Ordering {
    // sort objects
    match (a, b) {
        (Object::Map { content: a_map, .. }, Object::Map { content: b_map, .. }) => {
            compare_predicates(a_map, b_map)
        }
        _ => a.object().cmp(&b.object()),
    }
}

fn write_predicates(
    writer: &mut Writer<Cursor<Vec<u8>>>,
    prefixes: &Prefixes,
    predicates: &BTreeMap<String, Objects>,
) -> Result<(), XMLError> {
    let rdf_type = match &predicates
        .get(&iri(RDF, "type"))
        .expect("Valid rdf:type statement")
        .first()
        .expect("At least one object")
    {
        Object::ID { id, .. } => id,
        b => panic!("rdf:type must be an IRI: {b:?}"),
    };
    writer
        .create_element(qname(&prefixes, rdf_type))
        .write_inner_content(|writer| {
            let mut keys: Vec<String> = predicates.keys().map(|k| k.clone()).collect();
            keys.sort();

            // OWL API renders onProperty then qualifiedCardinality
            let qualified_cardinality = String::from(&iri(OWL, "qualifiedCardinality"));
            if keys.contains(&qualified_cardinality) {
                keys.retain(|k| k != &qualified_cardinality);
                keys.insert(0, qualified_cardinality);
            }
            let on_property = String::from(&iri(OWL, "onProperty"));
            if keys.contains(&on_property) {
                keys.retain(|k| k != &on_property);
                keys.insert(0, on_property);
            }

            for key in keys.iter() {
                // The rdf:type is already the element name
                if key == &iri(RDF, "type") {
                    continue;
                }
                let objects = predicates.get(key).unwrap();

                for object in objects.iter() {
                    match &object {
                        Object::ID { id, .. } => {
                            writer
                                .create_element(qname(&prefixes, key))
                                .with_attribute(("rdf:resource", id.as_str()))
                                .write_empty()?;
                        }
                        Object::Map { content: map, .. } => {
                            writer
                                .create_element(qname(&prefixes, key))
                                .write_inner_content(|writer| {
                                    write_predicates(writer, &prefixes, &map)
                                        .expect("recursion to work");
                                    Ok(())
                                })
                                .expect("Recursion to work");
                        }
                        Object::List { list: objects, .. } => {
                            writer
                                .create_element(qname(&prefixes, key))
                                .with_attribute(("rdf:parseType", "Collection"))
                                .write_inner_content(|writer| {
                                    write_objects(writer, &prefixes, objects)
                                        .expect("Recursion to work");
                                    Ok(())
                                })
                                .expect("Recursion to work");
                        }
                        Object::TypedLiteral {
                            datatype, value, ..
                        } => {
                            writer
                                .create_element(qname(&prefixes, key))
                                .with_attribute(("rdf:datatype", datatype.as_str()))
                                .write_text_content(BytesText::new(&value))
                                .expect("Recursion to work");
                        }
                        o => panic!("Unexpected object {o:?}"),
                    };
                }
            }
            Ok(())
        })?;
    Ok(())
}

fn write_objects<'a>(
    writer: &'a mut Writer<Cursor<Vec<u8>>>,
    prefixes: &Prefixes,
    objects: &Vec<Object>,
) -> Result<&'a mut Writer<Cursor<Vec<u8>>>, XMLError> {
    for object in objects.iter() {
        match &object {
            Object::ID { id, .. } => {
                writer
                    .create_element("rdf:Description")
                    .with_attribute(("rdf:about", id.as_str()))
                    .write_empty()?;
            }
            Object::Map { content: map, .. } => {
                write_predicates(writer, prefixes, &map)?;
            }
            _ => todo!(),
        };
    }
    Ok(writer)
}

fn write_predicate_object(
    writer: &mut Writer<Cursor<Vec<u8>>>,
    prefixes: &Prefixes,
    predicate: &str,
    object: &Object,
) -> Result<(), XMLError> {
    match object {
        Object::ID { id, .. } => writer
            .create_element(qname(prefixes, predicate))
            .with_attribute(("rdf:resource", id.as_str()))
            .write_empty()?,
        Object::LanguageLiteral {
            value, language, ..
        } => writer
            .create_element(qname(prefixes, predicate))
            .with_attribute(("xml:lang", language.as_str()))
            .write_text_content(BytesText::from_escaped(value))?,
        Object::TypedLiteral {
            value, datatype, ..
        } if datatype == PLAIN => writer
            .create_element(qname(prefixes, predicate))
            .write_text_content(BytesText::from_escaped(value))?,
        Object::TypedLiteral {
            value, datatype, ..
        } => writer
            .create_element(qname(prefixes, predicate))
            .with_attribute(("rdf:datatype", datatype.as_str()))
            .write_text_content(BytesText::from_escaped(value))?,
        Object::List { list: objects, .. } => writer
            .create_element(qname(prefixes, predicate))
            .with_attribute(("rdf:parseType", "Collection"))
            .write_inner_content(|writer| {
                write_objects(writer, prefixes, &objects).expect("write objects");
                Ok(())
            })
            .expect("write list to work"),
        Object::Map { content: map, .. } => writer
            .create_element(qname(prefixes, predicate))
            .write_inner_content(|writer| {
                write_predicates(writer, prefixes, &map).expect("recursion to work");
                Ok(())
            })
            .expect("Recursion to work"),
    };
    Ok(())
}

const RDF: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
const RDFS: &str = "http://www.w3.org/2000/01/rdf-schema#";
const OWL: &str = "http://www.w3.org/2002/07/owl#";

fn iri(prefix: &str, local_name: &str) -> String {
    format!("{prefix}{local_name}")
}

// TODO: This is a hack
fn qname(prefixes: &Prefixes, iri: &str) -> String {
    prefixes.compact(iri)
}

pub fn write_to_string(graph: &IndexedMemoryGraph) -> Result<String, XMLError> {
    let mut writer = Writer::new_with_indent(Cursor::new(Vec::new()), b' ', 4);
    writer.write_event(Event::Decl(BytesDecl::new("1.0", None, None)))?;
    writer.write_event(Event::Text(BytesText::new("\n")))?;

    // Get special annotations tracking the prefixes and OWLAPI version.
    let mut rdf_declarations = String::new();
    let mut rdf_generator =
        String::from(" Generated by the OWL API (version 4.5.29) https://github.com/owlcs/owlapi ");
    let graph_triples = graph
        .get("http://example.com/graph")
        .and_then(|g| Some(g.triples()))
        .unwrap_or_default();
    for triple in graph_triples.iter() {
        if triple.predicate == "http://example.com/rdf_declarations" {
            rdf_declarations = triple.object.object();
        } else if triple.predicate == "http://example.com/rdf_generator" {
            rdf_generator = triple.object.object();
        }
    }
    if rdf_declarations == "" {
        panic!("Did not find any XML namespace declarations");
    }

    let content = format!("rdf:RDF{rdf_declarations}");
    let elem = BytesStart::from_content(content.as_str(), 7);

    let mut prefixes = Prefixes::new();
    for attr in elem.attributes() {
        match attr {
            Ok(attr) => match attr.key.prefix() {
                Some(p) => {
                    if p.into_inner() == "xmlns".as_bytes() {
                        let prefix = String::from_utf8(attr.key.local_name().into_inner().to_vec())
                            .expect("Valid local name");
                        let iri = String::from_utf8(attr.value.into_owned())
                            .expect("Valid attribute value");
                        prefixes.insert(&prefix, &iri);
                    }
                }
                None => continue,
            },
            Err(_) => continue,
        }
    }
    // println!("PREFIXES {prefixes:?}");

    writer.write_event(Event::Start(elem))?;
    writer.write_event(Event::Text(BytesText::new("\n    ")))?;

    let mut ontology = String::new();
    let mut annotation_properties = BTreeSet::new();
    let mut datatypes = BTreeSet::new();
    let mut object_properties = BTreeSet::new();
    let mut datatype_properties = BTreeSet::new();
    let mut classes = BTreeSet::new();
    let mut individuals = BTreeSet::new();
    let mut annotations = BTreeSet::new();
    let mut general_axioms = BTreeSet::new();

    for subject in graph.subjects() {
        let id = subject.name();

        if id.starts_with("hash:") {
            general_axioms.insert(id);
            continue;
        }

        // if !id.starts_with("http") {
        //     println!("Non HTTP {id} {subject:#?}");
        //     continue;
        // } else if id == "https://w3id.org/sssom/mapping_justification" {
        //     continue;
        // }

        for rdf_type in subject.types() {
            match rdf_type {
                "http://www.w3.org/2002/07/owl#Ontology" => {
                    ontology = id.to_string();
                }
                "http://www.w3.org/2002/07/owl#AnnotationProperty" => {
                    annotation_properties.insert(id.to_string());
                }
                "http://www.w3.org/2000/01/rdf-schema#Datatype" => {
                    datatypes.insert(id.to_string());
                }
                "http://www.w3.org/2002/07/owl#ObjectProperty" => {
                    object_properties.insert(id.to_string());
                }
                "http://www.w3.org/2002/07/owl#DatatypeProperty" => {
                    datatype_properties.insert(id.to_string());
                }
                "http://www.w3.org/2002/07/owl#Class" => {
                    classes.insert(id.to_string());
                }
                "http://www.w3.org/2002/07/owl#NamedIndividual"
                | "http://www.w3.org/2002/07/owl#Thing" => {
                    individuals.insert(id.to_string());
                }
                "http://www.w3.org/1999/02/22-rdf-syntax-ns#Description" => {
                    annotations.insert(id.to_string());
                }
                "http://www.w3.org/2002/07/owl#FunctionalProperty"
                | "http://www.w3.org/2002/07/owl#TransitiveProperty"
                | "http://www.w3.org/2002/07/owl#SymmetricProperty"
                | "http://www.w3.org/2002/07/owl#IrreflexiveProperty" => (),
                _ => (),
            }
        }
    }

    let properties = Properties {
        object: object_properties.clone(),
    };
    // println!("PROPERTIES {properties:?}");

    // Write owl:Ontology element
    write_subject(
        &mut writer,
        &prefixes,
        &properties,
        &iri(OWL, "Ontology"),
        graph.get(&ontology).expect("ontology to exist"),
    )?;

    write_section(
        &mut writer,
        graph,
        &prefixes,
        &properties,
        "Annotation properties",
        &iri(OWL, "AnnotationProperty"),
        &annotation_properties,
    )?;
    write_section(
        &mut writer,
        graph,
        &prefixes,
        &properties,
        "Datatypes",
        &iri(RDFS, "Datatype"),
        &datatypes,
    )?;
    write_section(
        &mut writer,
        graph,
        &prefixes,
        &properties,
        "Object Properties",
        &iri(OWL, "ObjectProperty"),
        &object_properties,
    )?;
    write_section(
        &mut writer,
        graph,
        &prefixes,
        &properties,
        "Data properties",
        &iri(OWL, "DatatypeProperty"),
        &datatype_properties,
    )?;
    write_section(
        &mut writer,
        graph,
        &prefixes,
        &properties,
        "Classes",
        &iri(OWL, "Class"),
        &classes,
    )?;
    write_section(
        &mut writer,
        graph,
        &prefixes,
        &properties,
        "Individuals",
        &iri(OWL, "NamedIndividual"),
        &individuals,
    )?;
    write_section(
        &mut writer,
        graph,
        &prefixes,
        &properties,
        "Annotations",
        &iri(RDF, "Description"),
        &annotations,
    )?;
    write_section(
        &mut writer,
        graph,
        &prefixes,
        &properties,
        "General axioms",
        &iri(RDF, "Description"),
        &general_axioms,
    )?;
    writer.write_event(Event::End(BytesEnd::new("rdf:RDF")))?;
    writer.write_event(Event::Text(BytesText::new("\n\n\n\n")))?;
    writer.write_event(Event::Comment(BytesText::new(&rdf_generator)))?;
    writer.write_event(Event::Text(BytesText::new("\n\n")))?;

    let result = writer.into_inner().into_inner();
    Ok(String::from_utf8(result).expect("Valid UTF-8"))
}

#[cfg(test)]
mod tests {
    use std::{
        cmp::Ordering,
        collections::{BTreeMap, BTreeSet},
    };

    use crate::{
        model::{ALL_VALUES_FROM, CLASS, ON_PROPERTY, Object, RESTRICTION, SOME_VALUES_FROM, TYPE},
        rdfxml::compare_objects,
    };

    #[test]
    fn test_compare_objects() {
        let a = Object::map(BTreeMap::from([
            (TYPE.to_string(), BTreeSet::from([Object::id(RESTRICTION)])),
            (
                ON_PROPERTY.to_string(),
                BTreeSet::from([Object::id("http://purl.obolibrary.org/obo/RO_0000079")]),
            ),
            (
                SOME_VALUES_FROM.to_string(),
                BTreeSet::from([Object::id("http://purl.obolibrary.org/obo/COB_0000026")]),
            ),
        ]));
        let b = Object::map(BTreeMap::from([
            (TYPE.to_string(), BTreeSet::from([Object::id(RESTRICTION)])),
            (
                ON_PROPERTY.to_string(),
                BTreeSet::from([Object::id("http://purl.obolibrary.org/obo/BFO_0000054")]),
            ),
            (
                ALL_VALUES_FROM.to_string(),
                BTreeSet::from([Object::map(BTreeMap::from([
                    (TYPE.to_string(), BTreeSet::from([Object::id(RESTRICTION)])),
                    (
                        ON_PROPERTY.to_string(),
                        BTreeSet::from([Object::id("http://purl.obolibrary.org/obo/OBI_0000299")]),
                    ),
                    (
                        SOME_VALUES_FROM.to_string(),
                        BTreeSet::from([Object::id("http://purl.obolibrary.org/obo/IAO_0000109")]),
                    ),
                ]))]),
            ),
        ]));
        let c = Object::map(BTreeMap::from([(
            TYPE.to_string(),
            BTreeSet::from([Object::id(CLASS)]),
        )]));

        assert_eq!(
            Ordering::Less,
            compare_objects(&a, &b),
            "someValuesFrom before allValuesFrom"
        );
        assert_eq!(
            Ordering::Less,
            compare_objects(&c, &a),
            "Class before Restriction"
        );
        assert!(false, "DONE");
    }
}
